name: quiz_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.1
  flutter_svg: ^2.0.2
  flutter_switch: ^0.3.2
  image_picker: ^0.8.7
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/
    - fonts/
    - fonts/nunito_sans/
    - fonts/rubik/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/nunito_sans/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/nunito_sans/NunitoSans-Bold.ttf
          weight: 700
        - asset: fonts/nunito_sans/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: fonts/nunito_sans/NunitoSans-Regular.ttf
          weight: 400
        - asset: fonts/nunito_sans/NunitoSans-Light.ttf
          weight: 300
        - asset: fonts/nunito_sans/NunitoSans-ExtraLight.ttf
          weight: 200
    - family: Rubik
      fonts:
        - asset: fonts/rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/rubik/Rubik-Regular.ttf
          weight: 400
        - asset: fonts/rubik/Rubik-Light.ttf
          weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
